version: 2
updates:
  # Backend Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
      - "security"
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - "gonzacba17"
    assignees:
      - "gonzacba17"
  
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "frontend"
      - "security"
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - "gonzacba17"
    assignees:
      - "gonzacba17"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - "gonzacba17"
