version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cafeteria_ia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - saas_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - saas_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/cafeteria_ia
      - SECRET_KEY=your-secret-key-here
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MERCADOPAGO_KEY=${MERCADOPAGO_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - saas_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - saas_network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  saas_network:
    driver: bridge