# Prometheus Configuration for SaaS Cafeterías
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'saas-cafeterias'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI Backend Metrics
  - job_name: 'saas-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  # FastAPI Health Checks
  - job_name: 'saas-backend-health'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/health'
    scrape_interval: 30s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  # cAdvisor (Container Metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  # PostgreSQL Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # Blackbox Exporter (HTTP Probes)
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://backend:8000/health
        - http://frontend:3000
        - http://backend:8000/api/v1/auth/me
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  # Celery Worker Metrics (if available)
  - job_name: 'celery-worker'
    static_configs:
      - targets: ['celery-worker:8888']  # Assumes celery prometheus exporter
    scrape_interval: 30s

  # Flower Celery Monitoring
  - job_name: 'flower'
    static_configs:
      - targets: ['flower:5555']
    metrics_path: '/api/workers'
    scrape_interval: 30s

  # Custom Business Metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 60s
    params:
      format: ['prometheus']