apiVersion: 1

datasources:
  # Prometheus Datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
    
  # Elasticsearch Datasource for Logs
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[saas-logs-*]"
    jsonData:
      interval: "Daily"
      timeField: "@timestamp"
      esVersion: "8.10.0"
      logMessageField: "message"
      logLevelField: "level"
    editable: false
    
  # Loki Datasource (if using Grafana Loki)
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: "prometheus"
          matcherRegex: "traceID=(\\w+)"
          name: "TraceID"
          url: "${__value.raw}"