filebeat.inputs:
  # Backend Application Logs
  - type: log
    enabled: true
    paths:
      - /var/log/backend/*.log
    fields:
      service: saas-backend
      environment: production
    fields_under_root: true
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after
    json.keys_under_root: true
    json.add_error_key: true
    
  # Docker Container Logs
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
    fields:
      environment: production
    
  # System Logs
  - type: log
    enabled: true
    paths:
      - /var/log/messages
      - /var/log/syslog
      - /var/log/auth.log
    fields:
      log_type: system
      environment: production

# Output to Elasticsearch
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "saas-logs-%{+yyyy.MM.dd}"
  
# Configure Kibana endpoint for dashboards
setup.kibana:
  host: "kibana:5601"

# Index template settings
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 1
  index.refresh_interval: "5s"

# Processors for log enhancement
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_fields:
      target: "saas"
      fields:
        application: "saas-cafeterias"
        version: "1.0.0"
  - timestamp:
      field: "@timestamp"
      layouts:
        - '2006-01-02T15:04:05.000Z'
        - '2006-01-02T15:04:05Z'
      test:
        - '2023-08-15T14:30:45.123Z'

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["elasticsearch:9200"]